title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: false
theme: jekyll-theme-cayman

conference_name: "ECIR 2026 Conversational Search Tutorial"
conference_cikm: "at the 48th European Conference on Information Retrieval (ECIR 2026)"
conference_venue: "2026"
conference_intro: "Will be held in 2026"
google_analytics: G-T8FCCBB6BD

github:
  zip_url: http://www.google.com

collections:
  ecir2026_organisers:
    output: true
  sigir2025_organisers:
    output: true
  speakers:
    output: true
